### лист моделей
GET https://api.mistral.ai/v1/models
Authorization: Bearer rdA1PQcxj6FVQGLZCjlrNWKh2YGTVLsA

### Как получить chatId
POST https://api.mistral.ai/v1/chat/completions
Authorization: Bearer rdA1PQcxj6FVQGLZCjlrNWKh2YGTVLsA
Content-Type: application/json

{
  "model": "open-mistral-7b",
  "messages": [
    { "role": "user", "content": "Привет!" },
    { "role": "assistant", "content": "Привет! Как дела? Могу тебе помочь с чем-то?" },
    { "role": "user", "content": "Сколько будет 2 + 2?" }
  ]
}


### запрос чату получить айди
POST http://localhost:8080/api/chat/new
Content-Type: application/json

### запрос чату
POST http://localhost:8080/api/ask
Content-Type: application/json

{
  "chatId": "a994af33-77e8-4d59-b892-3921c2029877",
  "question": "Кто ты?"
}

### запрос чату
POST http://localhost:8080/api/ask
Content-Type: application/json

{
  "chatId": "318b6743-cb7b-447b-9835-653e3d4ccbd9",
  "question": "Меня зовут Артем?"
}

### запрос чату
POST http://localhost:8080/api/ask
Content-Type: application/json

{
  "chatId": "318b6743-cb7b-447b-9835-653e3d4ccbd9",
  "question": "Ты помнишь мое имя?"
}

### запрос чату
POST http://localhost:8080/api/ask
Content-Type: application/json

{
  "chatId": "abb2462e-1d15-4056-8844-b156366d51de",
  "question": "Кто такой зелепук?"
}

### load
GET http://localhost:8080/api/documents/load
Content-Type: application/json
