### лист моделей
GET https://api.mistral.ai/v1/models
Authorization: Bearer rdA1PQcxj6FVQGLZCjlrNWKh2YGTVLsA

### Как получить chatId
POST https://api.mistral.ai/v1/chat/completions
Authorization: Bearer rdA1PQcxj6FVQGLZCjlrNWKh2YGTVLsA
Content-Type: application/json

{
  "model": "open-mistral-7b",
  "messages": [
    { "role": "user", "content": "Привет!" },
    { "role": "assistant", "content": "Привет! Как дела? Могу тебе помочь с чем-то?" },
    { "role": "user", "content": "Сколько будет 2 + 2?" }
  ]
}


### запрос чату получить айди
POST http://localhost:8080/api/chat/new
Content-Type: application/json


### запрос чату
POST http://localhost:8080/api/ask
Content-Type: application/json

{
  "chatId": "48b8f86a-8ffc-4f40-b150-da46e2279f30",
  "question": "Меня зовут Артем?"
}

### запрос чату
POST http://localhost:8080/api/ask
Content-Type: application/json

{
  "chatId": "48b8f86a-8ffc-4f40-b150-da46e2279f30",
  "question": "Ты помнишь мое имя?"
}
